### ISSUE TITLE
Peer to peer code review Drop down mobile menu

### ISSUE THREAD

**Issue by DavidCazco36** [anas599/anas599.github.io#5]
Leave your comments here:

**Comment by DavidCazco36** [comment]
- Well organized code and simple and easy to read.
- It would be great if you add a transition or animation to dropdown menu.
- Good job in general.

**Comment by astroboyReloaded** [comment]
## Verry pro-looking code!
- I noticed some commented-out code in the CSS files.
- Maybe a transition for the mobile menu btn would make it look even a bit nicer.
- I think there is opportunity to improve the README.md.

**Comment by Grandi0z** [comment]
- Good code 
- Clean and easy to read
- It will be better if you give descritive names to your js variables
